/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSystemRouteRouteImport } from './routes/_authenticated/system/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedPlatformRouteRouteImport } from './routes/_authenticated/platform/route'
import { Route as authSignInRouteRouteImport } from './routes/(auth)/sign-in/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as authSignInTenantRouteImport } from './routes/(auth)/sign-in/tenant'
import { Route as authSignInPlatformRouteImport } from './routes/(auth)/sign-in/platform'
import { Route as AuthenticatedSystemUsersIndexRouteImport } from './routes/_authenticated/system/users/index'
import { Route as AuthenticatedSystemRolesIndexRouteImport } from './routes/_authenticated/system/roles/index'
import { Route as AuthenticatedPurchaseReplenishIndexRouteImport } from './routes/_authenticated/purchase/replenish/index'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase/orders/index'
import { Route as AuthenticatedPlatformTenantsIndexRouteImport } from './routes/_authenticated/platform/tenants/index'
import { Route as AuthenticatedPlatformMenusIndexRouteImport } from './routes/_authenticated/platform/menus/index'
import { Route as AuthenticatedOperationSalesIndexRouteImport } from './routes/_authenticated/operation/sales/index'
import { Route as AuthenticatedOperationRefundsIndexRouteImport } from './routes/_authenticated/operation/refunds/index'
import { Route as AuthenticatedOperationPaymentsIndexRouteImport } from './routes/_authenticated/operation/payments/index'
import { Route as AuthenticatedOperationCashierShiftsIndexRouteImport } from './routes/_authenticated/operation/cashier-shifts/index'
import { Route as AuthenticatedOnlineStoreConfigIndexRouteImport } from './routes/_authenticated/online/store-config/index'
import { Route as AuthenticatedOnlineProductsIndexRouteImport } from './routes/_authenticated/online/products/index'
import { Route as AuthenticatedOnlineDeliveriesIndexRouteImport } from './routes/_authenticated/online/deliveries/index'
import { Route as AuthenticatedMemberPointsIndexRouteImport } from './routes/_authenticated/member/points/index'
import { Route as AuthenticatedMemberMembersIndexRouteImport } from './routes/_authenticated/member/members/index'
import { Route as AuthenticatedMemberCouponsIndexRouteImport } from './routes/_authenticated/member/coupons/index'
import { Route as AuthenticatedInventoryTransfersIndexRouteImport } from './routes/_authenticated/inventory/transfers/index'
import { Route as AuthenticatedInventoryStockIndexRouteImport } from './routes/_authenticated/inventory/stock/index'
import { Route as AuthenticatedInventoryReceiptsIndexRouteImport } from './routes/_authenticated/inventory/receipts/index'
import { Route as AuthenticatedInventoryIssuesIndexRouteImport } from './routes/_authenticated/inventory/issues/index'
import { Route as AuthenticatedInventoryChecksIndexRouteImport } from './routes/_authenticated/inventory/checks/index'
import { Route as AuthenticatedFinanceVouchersIndexRouteImport } from './routes/_authenticated/finance/vouchers/index'
import { Route as AuthenticatedFinanceSupplierSettlementIndexRouteImport } from './routes/_authenticated/finance/supplier-settlement/index'
import { Route as AuthenticatedFinanceStoreSettlementIndexRouteImport } from './routes/_authenticated/finance/store-settlement/index'
import { Route as AuthenticatedFinanceFeesIndexRouteImport } from './routes/_authenticated/finance/fees/index'
import { Route as AuthenticatedArchiveWarehousesIndexRouteImport } from './routes/_authenticated/archive/warehouses/index'
import { Route as AuthenticatedArchiveSuppliersIndexRouteImport } from './routes/_authenticated/archive/suppliers/index'
import { Route as AuthenticatedArchiveStoresIndexRouteImport } from './routes/_authenticated/archive/stores/index'
import { Route as AuthenticatedArchiveProductsIndexRouteImport } from './routes/_authenticated/archive/products/index'
import { Route as AuthenticatedArchiveCategoriesIndexRouteImport } from './routes/_authenticated/archive/categories/index'
import { Route as AuthenticatedAnalyticsProductSalesIndexRouteImport } from './routes/_authenticated/analytics/product-sales/index'
import { Route as AuthenticatedAnalyticsInventoryIndexRouteImport } from './routes/_authenticated/analytics/inventory/index'
import { Route as AuthenticatedAnalyticsDailySalesIndexRouteImport } from './routes/_authenticated/analytics/daily-sales/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSystemRouteRoute =
  AuthenticatedSystemRouteRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRouteRoute =
  AuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSignInRouteRoute = authSignInRouteRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authSignInRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSignInTenantRoute = authSignInTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => authSignInRouteRoute,
} as any)
const authSignInPlatformRoute = authSignInPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => authSignInRouteRoute,
} as any)
const AuthenticatedSystemUsersIndexRoute =
  AuthenticatedSystemUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedSystemRolesIndexRoute =
  AuthenticatedSystemRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedSystemRouteRoute,
  } as any)
const AuthenticatedPurchaseReplenishIndexRoute =
  AuthenticatedPurchaseReplenishIndexRouteImport.update({
    id: '/purchase/replenish/',
    path: '/purchase/replenish/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase/orders/',
    path: '/purchase/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformTenantsIndexRoute =
  AuthenticatedPlatformTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformMenusIndexRoute =
  AuthenticatedPlatformMenusIndexRouteImport.update({
    id: '/menus/',
    path: '/menus/',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedOperationSalesIndexRoute =
  AuthenticatedOperationSalesIndexRouteImport.update({
    id: '/operation/sales/',
    path: '/operation/sales/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationRefundsIndexRoute =
  AuthenticatedOperationRefundsIndexRouteImport.update({
    id: '/operation/refunds/',
    path: '/operation/refunds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationPaymentsIndexRoute =
  AuthenticatedOperationPaymentsIndexRouteImport.update({
    id: '/operation/payments/',
    path: '/operation/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationCashierShiftsIndexRoute =
  AuthenticatedOperationCashierShiftsIndexRouteImport.update({
    id: '/operation/cashier-shifts/',
    path: '/operation/cashier-shifts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnlineStoreConfigIndexRoute =
  AuthenticatedOnlineStoreConfigIndexRouteImport.update({
    id: '/online/store-config/',
    path: '/online/store-config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnlineProductsIndexRoute =
  AuthenticatedOnlineProductsIndexRouteImport.update({
    id: '/online/products/',
    path: '/online/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnlineDeliveriesIndexRoute =
  AuthenticatedOnlineDeliveriesIndexRouteImport.update({
    id: '/online/deliveries/',
    path: '/online/deliveries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemberPointsIndexRoute =
  AuthenticatedMemberPointsIndexRouteImport.update({
    id: '/member/points/',
    path: '/member/points/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemberMembersIndexRoute =
  AuthenticatedMemberMembersIndexRouteImport.update({
    id: '/member/members/',
    path: '/member/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemberCouponsIndexRoute =
  AuthenticatedMemberCouponsIndexRouteImport.update({
    id: '/member/coupons/',
    path: '/member/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryTransfersIndexRoute =
  AuthenticatedInventoryTransfersIndexRouteImport.update({
    id: '/inventory/transfers/',
    path: '/inventory/transfers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryStockIndexRoute =
  AuthenticatedInventoryStockIndexRouteImport.update({
    id: '/inventory/stock/',
    path: '/inventory/stock/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryReceiptsIndexRoute =
  AuthenticatedInventoryReceiptsIndexRouteImport.update({
    id: '/inventory/receipts/',
    path: '/inventory/receipts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIssuesIndexRoute =
  AuthenticatedInventoryIssuesIndexRouteImport.update({
    id: '/inventory/issues/',
    path: '/inventory/issues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryChecksIndexRoute =
  AuthenticatedInventoryChecksIndexRouteImport.update({
    id: '/inventory/checks/',
    path: '/inventory/checks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceVouchersIndexRoute =
  AuthenticatedFinanceVouchersIndexRouteImport.update({
    id: '/finance/vouchers/',
    path: '/finance/vouchers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceSupplierSettlementIndexRoute =
  AuthenticatedFinanceSupplierSettlementIndexRouteImport.update({
    id: '/finance/supplier-settlement/',
    path: '/finance/supplier-settlement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceStoreSettlementIndexRoute =
  AuthenticatedFinanceStoreSettlementIndexRouteImport.update({
    id: '/finance/store-settlement/',
    path: '/finance/store-settlement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceFeesIndexRoute =
  AuthenticatedFinanceFeesIndexRouteImport.update({
    id: '/finance/fees/',
    path: '/finance/fees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveWarehousesIndexRoute =
  AuthenticatedArchiveWarehousesIndexRouteImport.update({
    id: '/archive/warehouses/',
    path: '/archive/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveSuppliersIndexRoute =
  AuthenticatedArchiveSuppliersIndexRouteImport.update({
    id: '/archive/suppliers/',
    path: '/archive/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveStoresIndexRoute =
  AuthenticatedArchiveStoresIndexRouteImport.update({
    id: '/archive/stores/',
    path: '/archive/stores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveProductsIndexRoute =
  AuthenticatedArchiveProductsIndexRouteImport.update({
    id: '/archive/products/',
    path: '/archive/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveCategoriesIndexRoute =
  AuthenticatedArchiveCategoriesIndexRouteImport.update({
    id: '/archive/categories/',
    path: '/archive/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsProductSalesIndexRoute =
  AuthenticatedAnalyticsProductSalesIndexRouteImport.update({
    id: '/analytics/product-sales/',
    path: '/analytics/product-sales/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsInventoryIndexRoute =
  AuthenticatedAnalyticsInventoryIndexRouteImport.update({
    id: '/analytics/inventory/',
    path: '/analytics/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsDailySalesIndexRoute =
  AuthenticatedAnalyticsDailySalesIndexRouteImport.update({
    id: '/analytics/daily-sales/',
    path: '/analytics/daily-sales/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/sign-in': typeof authSignInRouteRouteWithChildren
  '/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/system': typeof AuthenticatedSystemRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$': typeof AuthenticatedSplatRoute
  '/sign-in/platform': typeof authSignInPlatformRoute
  '/sign-in/tenant': typeof authSignInTenantRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/analytics/daily-sales/': typeof AuthenticatedAnalyticsDailySalesIndexRoute
  '/analytics/inventory/': typeof AuthenticatedAnalyticsInventoryIndexRoute
  '/analytics/product-sales/': typeof AuthenticatedAnalyticsProductSalesIndexRoute
  '/archive/categories/': typeof AuthenticatedArchiveCategoriesIndexRoute
  '/archive/products/': typeof AuthenticatedArchiveProductsIndexRoute
  '/archive/stores/': typeof AuthenticatedArchiveStoresIndexRoute
  '/archive/suppliers/': typeof AuthenticatedArchiveSuppliersIndexRoute
  '/archive/warehouses/': typeof AuthenticatedArchiveWarehousesIndexRoute
  '/finance/fees/': typeof AuthenticatedFinanceFeesIndexRoute
  '/finance/store-settlement/': typeof AuthenticatedFinanceStoreSettlementIndexRoute
  '/finance/supplier-settlement/': typeof AuthenticatedFinanceSupplierSettlementIndexRoute
  '/finance/vouchers/': typeof AuthenticatedFinanceVouchersIndexRoute
  '/inventory/checks/': typeof AuthenticatedInventoryChecksIndexRoute
  '/inventory/issues/': typeof AuthenticatedInventoryIssuesIndexRoute
  '/inventory/receipts/': typeof AuthenticatedInventoryReceiptsIndexRoute
  '/inventory/stock/': typeof AuthenticatedInventoryStockIndexRoute
  '/inventory/transfers/': typeof AuthenticatedInventoryTransfersIndexRoute
  '/member/coupons/': typeof AuthenticatedMemberCouponsIndexRoute
  '/member/members/': typeof AuthenticatedMemberMembersIndexRoute
  '/member/points/': typeof AuthenticatedMemberPointsIndexRoute
  '/online/deliveries/': typeof AuthenticatedOnlineDeliveriesIndexRoute
  '/online/products/': typeof AuthenticatedOnlineProductsIndexRoute
  '/online/store-config/': typeof AuthenticatedOnlineStoreConfigIndexRoute
  '/operation/cashier-shifts/': typeof AuthenticatedOperationCashierShiftsIndexRoute
  '/operation/payments/': typeof AuthenticatedOperationPaymentsIndexRoute
  '/operation/refunds/': typeof AuthenticatedOperationRefundsIndexRoute
  '/operation/sales/': typeof AuthenticatedOperationSalesIndexRoute
  '/platform/menus/': typeof AuthenticatedPlatformMenusIndexRoute
  '/platform/tenants/': typeof AuthenticatedPlatformTenantsIndexRoute
  '/purchase/orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/purchase/replenish/': typeof AuthenticatedPurchaseReplenishIndexRoute
  '/system/roles/': typeof AuthenticatedSystemRolesIndexRoute
  '/system/users/': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/system': typeof AuthenticatedSystemRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$': typeof AuthenticatedSplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/sign-in/platform': typeof authSignInPlatformRoute
  '/sign-in/tenant': typeof authSignInTenantRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/sign-in': typeof authSignInIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/analytics/daily-sales': typeof AuthenticatedAnalyticsDailySalesIndexRoute
  '/analytics/inventory': typeof AuthenticatedAnalyticsInventoryIndexRoute
  '/analytics/product-sales': typeof AuthenticatedAnalyticsProductSalesIndexRoute
  '/archive/categories': typeof AuthenticatedArchiveCategoriesIndexRoute
  '/archive/products': typeof AuthenticatedArchiveProductsIndexRoute
  '/archive/stores': typeof AuthenticatedArchiveStoresIndexRoute
  '/archive/suppliers': typeof AuthenticatedArchiveSuppliersIndexRoute
  '/archive/warehouses': typeof AuthenticatedArchiveWarehousesIndexRoute
  '/finance/fees': typeof AuthenticatedFinanceFeesIndexRoute
  '/finance/store-settlement': typeof AuthenticatedFinanceStoreSettlementIndexRoute
  '/finance/supplier-settlement': typeof AuthenticatedFinanceSupplierSettlementIndexRoute
  '/finance/vouchers': typeof AuthenticatedFinanceVouchersIndexRoute
  '/inventory/checks': typeof AuthenticatedInventoryChecksIndexRoute
  '/inventory/issues': typeof AuthenticatedInventoryIssuesIndexRoute
  '/inventory/receipts': typeof AuthenticatedInventoryReceiptsIndexRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockIndexRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersIndexRoute
  '/member/coupons': typeof AuthenticatedMemberCouponsIndexRoute
  '/member/members': typeof AuthenticatedMemberMembersIndexRoute
  '/member/points': typeof AuthenticatedMemberPointsIndexRoute
  '/online/deliveries': typeof AuthenticatedOnlineDeliveriesIndexRoute
  '/online/products': typeof AuthenticatedOnlineProductsIndexRoute
  '/online/store-config': typeof AuthenticatedOnlineStoreConfigIndexRoute
  '/operation/cashier-shifts': typeof AuthenticatedOperationCashierShiftsIndexRoute
  '/operation/payments': typeof AuthenticatedOperationPaymentsIndexRoute
  '/operation/refunds': typeof AuthenticatedOperationRefundsIndexRoute
  '/operation/sales': typeof AuthenticatedOperationSalesIndexRoute
  '/platform/menus': typeof AuthenticatedPlatformMenusIndexRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsIndexRoute
  '/purchase/orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/purchase/replenish': typeof AuthenticatedPurchaseReplenishIndexRoute
  '/system/roles': typeof AuthenticatedSystemRolesIndexRoute
  '/system/users': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRouteRouteWithChildren
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/system': typeof AuthenticatedSystemRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/(auth)/sign-in/platform': typeof authSignInPlatformRoute
  '/(auth)/sign-in/tenant': typeof authSignInTenantRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/analytics/daily-sales/': typeof AuthenticatedAnalyticsDailySalesIndexRoute
  '/_authenticated/analytics/inventory/': typeof AuthenticatedAnalyticsInventoryIndexRoute
  '/_authenticated/analytics/product-sales/': typeof AuthenticatedAnalyticsProductSalesIndexRoute
  '/_authenticated/archive/categories/': typeof AuthenticatedArchiveCategoriesIndexRoute
  '/_authenticated/archive/products/': typeof AuthenticatedArchiveProductsIndexRoute
  '/_authenticated/archive/stores/': typeof AuthenticatedArchiveStoresIndexRoute
  '/_authenticated/archive/suppliers/': typeof AuthenticatedArchiveSuppliersIndexRoute
  '/_authenticated/archive/warehouses/': typeof AuthenticatedArchiveWarehousesIndexRoute
  '/_authenticated/finance/fees/': typeof AuthenticatedFinanceFeesIndexRoute
  '/_authenticated/finance/store-settlement/': typeof AuthenticatedFinanceStoreSettlementIndexRoute
  '/_authenticated/finance/supplier-settlement/': typeof AuthenticatedFinanceSupplierSettlementIndexRoute
  '/_authenticated/finance/vouchers/': typeof AuthenticatedFinanceVouchersIndexRoute
  '/_authenticated/inventory/checks/': typeof AuthenticatedInventoryChecksIndexRoute
  '/_authenticated/inventory/issues/': typeof AuthenticatedInventoryIssuesIndexRoute
  '/_authenticated/inventory/receipts/': typeof AuthenticatedInventoryReceiptsIndexRoute
  '/_authenticated/inventory/stock/': typeof AuthenticatedInventoryStockIndexRoute
  '/_authenticated/inventory/transfers/': typeof AuthenticatedInventoryTransfersIndexRoute
  '/_authenticated/member/coupons/': typeof AuthenticatedMemberCouponsIndexRoute
  '/_authenticated/member/members/': typeof AuthenticatedMemberMembersIndexRoute
  '/_authenticated/member/points/': typeof AuthenticatedMemberPointsIndexRoute
  '/_authenticated/online/deliveries/': typeof AuthenticatedOnlineDeliveriesIndexRoute
  '/_authenticated/online/products/': typeof AuthenticatedOnlineProductsIndexRoute
  '/_authenticated/online/store-config/': typeof AuthenticatedOnlineStoreConfigIndexRoute
  '/_authenticated/operation/cashier-shifts/': typeof AuthenticatedOperationCashierShiftsIndexRoute
  '/_authenticated/operation/payments/': typeof AuthenticatedOperationPaymentsIndexRoute
  '/_authenticated/operation/refunds/': typeof AuthenticatedOperationRefundsIndexRoute
  '/_authenticated/operation/sales/': typeof AuthenticatedOperationSalesIndexRoute
  '/_authenticated/platform/menus/': typeof AuthenticatedPlatformMenusIndexRoute
  '/_authenticated/platform/tenants/': typeof AuthenticatedPlatformTenantsIndexRoute
  '/_authenticated/purchase/orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/purchase/replenish/': typeof AuthenticatedPurchaseReplenishIndexRoute
  '/_authenticated/system/roles/': typeof AuthenticatedSystemRolesIndexRoute
  '/_authenticated/system/users/': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/sign-in'
    | '/platform'
    | '/settings'
    | '/system'
    | '/forgot-password'
    | '/otp'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$'
    | '/sign-in/platform'
    | '/sign-in/tenant'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/sign-in/'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/analytics/daily-sales/'
    | '/analytics/inventory/'
    | '/analytics/product-sales/'
    | '/archive/categories/'
    | '/archive/products/'
    | '/archive/stores/'
    | '/archive/suppliers/'
    | '/archive/warehouses/'
    | '/finance/fees/'
    | '/finance/store-settlement/'
    | '/finance/supplier-settlement/'
    | '/finance/vouchers/'
    | '/inventory/checks/'
    | '/inventory/issues/'
    | '/inventory/receipts/'
    | '/inventory/stock/'
    | '/inventory/transfers/'
    | '/member/coupons/'
    | '/member/members/'
    | '/member/points/'
    | '/online/deliveries/'
    | '/online/products/'
    | '/online/store-config/'
    | '/operation/cashier-shifts/'
    | '/operation/payments/'
    | '/operation/refunds/'
    | '/operation/sales/'
    | '/platform/menus/'
    | '/platform/tenants/'
    | '/purchase/orders/'
    | '/purchase/replenish/'
    | '/system/roles/'
    | '/system/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/platform'
    | '/system'
    | '/forgot-password'
    | '/otp'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$'
    | '/'
    | '/sign-in/platform'
    | '/sign-in/tenant'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/sign-in'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/analytics/daily-sales'
    | '/analytics/inventory'
    | '/analytics/product-sales'
    | '/archive/categories'
    | '/archive/products'
    | '/archive/stores'
    | '/archive/suppliers'
    | '/archive/warehouses'
    | '/finance/fees'
    | '/finance/store-settlement'
    | '/finance/supplier-settlement'
    | '/finance/vouchers'
    | '/inventory/checks'
    | '/inventory/issues'
    | '/inventory/receipts'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/member/coupons'
    | '/member/members'
    | '/member/points'
    | '/online/deliveries'
    | '/online/products'
    | '/online/store-config'
    | '/operation/cashier-shifts'
    | '/operation/payments'
    | '/operation/refunds'
    | '/operation/sales'
    | '/platform/menus'
    | '/platform/tenants'
    | '/purchase/orders'
    | '/purchase/replenish'
    | '/system/roles'
    | '/system/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/(auth)/sign-in'
    | '/_authenticated/platform'
    | '/_authenticated/settings'
    | '/_authenticated/system'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/$'
    | '/_authenticated/'
    | '/(auth)/sign-in/platform'
    | '/(auth)/sign-in/tenant'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/(auth)/sign-in/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/analytics/daily-sales/'
    | '/_authenticated/analytics/inventory/'
    | '/_authenticated/analytics/product-sales/'
    | '/_authenticated/archive/categories/'
    | '/_authenticated/archive/products/'
    | '/_authenticated/archive/stores/'
    | '/_authenticated/archive/suppliers/'
    | '/_authenticated/archive/warehouses/'
    | '/_authenticated/finance/fees/'
    | '/_authenticated/finance/store-settlement/'
    | '/_authenticated/finance/supplier-settlement/'
    | '/_authenticated/finance/vouchers/'
    | '/_authenticated/inventory/checks/'
    | '/_authenticated/inventory/issues/'
    | '/_authenticated/inventory/receipts/'
    | '/_authenticated/inventory/stock/'
    | '/_authenticated/inventory/transfers/'
    | '/_authenticated/member/coupons/'
    | '/_authenticated/member/members/'
    | '/_authenticated/member/points/'
    | '/_authenticated/online/deliveries/'
    | '/_authenticated/online/products/'
    | '/_authenticated/online/store-config/'
    | '/_authenticated/operation/cashier-shifts/'
    | '/_authenticated/operation/payments/'
    | '/_authenticated/operation/refunds/'
    | '/_authenticated/operation/sales/'
    | '/_authenticated/platform/menus/'
    | '/_authenticated/platform/tenants/'
    | '/_authenticated/purchase/orders/'
    | '/_authenticated/purchase/replenish/'
    | '/_authenticated/system/roles/'
    | '/_authenticated/system/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authSignInRouteRoute: typeof authSignInRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authSignInRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in/tenant': {
      id: '/(auth)/sign-in/tenant'
      path: '/tenant'
      fullPath: '/sign-in/tenant'
      preLoaderRoute: typeof authSignInTenantRouteImport
      parentRoute: typeof authSignInRouteRoute
    }
    '/(auth)/sign-in/platform': {
      id: '/(auth)/sign-in/platform'
      path: '/platform'
      fullPath: '/sign-in/platform'
      preLoaderRoute: typeof authSignInPlatformRouteImport
      parentRoute: typeof authSignInRouteRoute
    }
    '/_authenticated/system/users/': {
      id: '/_authenticated/system/users/'
      path: '/users'
      fullPath: '/system/users/'
      preLoaderRoute: typeof AuthenticatedSystemUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/system/roles/': {
      id: '/_authenticated/system/roles/'
      path: '/roles'
      fullPath: '/system/roles/'
      preLoaderRoute: typeof AuthenticatedSystemRolesIndexRouteImport
      parentRoute: typeof AuthenticatedSystemRouteRoute
    }
    '/_authenticated/purchase/replenish/': {
      id: '/_authenticated/purchase/replenish/'
      path: '/purchase/replenish'
      fullPath: '/purchase/replenish/'
      preLoaderRoute: typeof AuthenticatedPurchaseReplenishIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/orders/': {
      id: '/_authenticated/purchase/orders/'
      path: '/purchase/orders'
      fullPath: '/purchase/orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/tenants/': {
      id: '/_authenticated/platform/tenants/'
      path: '/tenants'
      fullPath: '/platform/tenants/'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/menus/': {
      id: '/_authenticated/platform/menus/'
      path: '/menus'
      fullPath: '/platform/menus/'
      preLoaderRoute: typeof AuthenticatedPlatformMenusIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/operation/sales/': {
      id: '/_authenticated/operation/sales/'
      path: '/operation/sales'
      fullPath: '/operation/sales/'
      preLoaderRoute: typeof AuthenticatedOperationSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation/refunds/': {
      id: '/_authenticated/operation/refunds/'
      path: '/operation/refunds'
      fullPath: '/operation/refunds/'
      preLoaderRoute: typeof AuthenticatedOperationRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation/payments/': {
      id: '/_authenticated/operation/payments/'
      path: '/operation/payments'
      fullPath: '/operation/payments/'
      preLoaderRoute: typeof AuthenticatedOperationPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operation/cashier-shifts/': {
      id: '/_authenticated/operation/cashier-shifts/'
      path: '/operation/cashier-shifts'
      fullPath: '/operation/cashier-shifts/'
      preLoaderRoute: typeof AuthenticatedOperationCashierShiftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online/store-config/': {
      id: '/_authenticated/online/store-config/'
      path: '/online/store-config'
      fullPath: '/online/store-config/'
      preLoaderRoute: typeof AuthenticatedOnlineStoreConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online/products/': {
      id: '/_authenticated/online/products/'
      path: '/online/products'
      fullPath: '/online/products/'
      preLoaderRoute: typeof AuthenticatedOnlineProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online/deliveries/': {
      id: '/_authenticated/online/deliveries/'
      path: '/online/deliveries'
      fullPath: '/online/deliveries/'
      preLoaderRoute: typeof AuthenticatedOnlineDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/points/': {
      id: '/_authenticated/member/points/'
      path: '/member/points'
      fullPath: '/member/points/'
      preLoaderRoute: typeof AuthenticatedMemberPointsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/members/': {
      id: '/_authenticated/member/members/'
      path: '/member/members'
      fullPath: '/member/members/'
      preLoaderRoute: typeof AuthenticatedMemberMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/coupons/': {
      id: '/_authenticated/member/coupons/'
      path: '/member/coupons'
      fullPath: '/member/coupons/'
      preLoaderRoute: typeof AuthenticatedMemberCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/transfers/': {
      id: '/_authenticated/inventory/transfers/'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers/'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/stock/': {
      id: '/_authenticated/inventory/stock/'
      path: '/inventory/stock'
      fullPath: '/inventory/stock/'
      preLoaderRoute: typeof AuthenticatedInventoryStockIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/receipts/': {
      id: '/_authenticated/inventory/receipts/'
      path: '/inventory/receipts'
      fullPath: '/inventory/receipts/'
      preLoaderRoute: typeof AuthenticatedInventoryReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/issues/': {
      id: '/_authenticated/inventory/issues/'
      path: '/inventory/issues'
      fullPath: '/inventory/issues/'
      preLoaderRoute: typeof AuthenticatedInventoryIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/checks/': {
      id: '/_authenticated/inventory/checks/'
      path: '/inventory/checks'
      fullPath: '/inventory/checks/'
      preLoaderRoute: typeof AuthenticatedInventoryChecksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/vouchers/': {
      id: '/_authenticated/finance/vouchers/'
      path: '/finance/vouchers'
      fullPath: '/finance/vouchers/'
      preLoaderRoute: typeof AuthenticatedFinanceVouchersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/supplier-settlement/': {
      id: '/_authenticated/finance/supplier-settlement/'
      path: '/finance/supplier-settlement'
      fullPath: '/finance/supplier-settlement/'
      preLoaderRoute: typeof AuthenticatedFinanceSupplierSettlementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/store-settlement/': {
      id: '/_authenticated/finance/store-settlement/'
      path: '/finance/store-settlement'
      fullPath: '/finance/store-settlement/'
      preLoaderRoute: typeof AuthenticatedFinanceStoreSettlementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/fees/': {
      id: '/_authenticated/finance/fees/'
      path: '/finance/fees'
      fullPath: '/finance/fees/'
      preLoaderRoute: typeof AuthenticatedFinanceFeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/warehouses/': {
      id: '/_authenticated/archive/warehouses/'
      path: '/archive/warehouses'
      fullPath: '/archive/warehouses/'
      preLoaderRoute: typeof AuthenticatedArchiveWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/suppliers/': {
      id: '/_authenticated/archive/suppliers/'
      path: '/archive/suppliers'
      fullPath: '/archive/suppliers/'
      preLoaderRoute: typeof AuthenticatedArchiveSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/stores/': {
      id: '/_authenticated/archive/stores/'
      path: '/archive/stores'
      fullPath: '/archive/stores/'
      preLoaderRoute: typeof AuthenticatedArchiveStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/products/': {
      id: '/_authenticated/archive/products/'
      path: '/archive/products'
      fullPath: '/archive/products/'
      preLoaderRoute: typeof AuthenticatedArchiveProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/categories/': {
      id: '/_authenticated/archive/categories/'
      path: '/archive/categories'
      fullPath: '/archive/categories/'
      preLoaderRoute: typeof AuthenticatedArchiveCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/product-sales/': {
      id: '/_authenticated/analytics/product-sales/'
      path: '/analytics/product-sales'
      fullPath: '/analytics/product-sales/'
      preLoaderRoute: typeof AuthenticatedAnalyticsProductSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/inventory/': {
      id: '/_authenticated/analytics/inventory/'
      path: '/analytics/inventory'
      fullPath: '/analytics/inventory/'
      preLoaderRoute: typeof AuthenticatedAnalyticsInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/daily-sales/': {
      id: '/_authenticated/analytics/daily-sales/'
      path: '/analytics/daily-sales'
      fullPath: '/analytics/daily-sales/'
      preLoaderRoute: typeof AuthenticatedAnalyticsDailySalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPlatformRouteRouteChildren {
  AuthenticatedPlatformMenusIndexRoute: typeof AuthenticatedPlatformMenusIndexRoute
  AuthenticatedPlatformTenantsIndexRoute: typeof AuthenticatedPlatformTenantsIndexRoute
}

const AuthenticatedPlatformRouteRouteChildren: AuthenticatedPlatformRouteRouteChildren =
  {
    AuthenticatedPlatformMenusIndexRoute: AuthenticatedPlatformMenusIndexRoute,
    AuthenticatedPlatformTenantsIndexRoute:
      AuthenticatedPlatformTenantsIndexRoute,
  }

const AuthenticatedPlatformRouteRouteWithChildren =
  AuthenticatedPlatformRouteRoute._addFileChildren(
    AuthenticatedPlatformRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSystemRouteRouteChildren {
  AuthenticatedSystemRolesIndexRoute: typeof AuthenticatedSystemRolesIndexRoute
  AuthenticatedSystemUsersIndexRoute: typeof AuthenticatedSystemUsersIndexRoute
}

const AuthenticatedSystemRouteRouteChildren: AuthenticatedSystemRouteRouteChildren =
  {
    AuthenticatedSystemRolesIndexRoute: AuthenticatedSystemRolesIndexRoute,
    AuthenticatedSystemUsersIndexRoute: AuthenticatedSystemUsersIndexRoute,
  }

const AuthenticatedSystemRouteRouteWithChildren =
  AuthenticatedSystemRouteRoute._addFileChildren(
    AuthenticatedSystemRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlatformRouteRoute: typeof AuthenticatedPlatformRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSystemRouteRoute: typeof AuthenticatedSystemRouteRouteWithChildren
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAnalyticsDailySalesIndexRoute: typeof AuthenticatedAnalyticsDailySalesIndexRoute
  AuthenticatedAnalyticsInventoryIndexRoute: typeof AuthenticatedAnalyticsInventoryIndexRoute
  AuthenticatedAnalyticsProductSalesIndexRoute: typeof AuthenticatedAnalyticsProductSalesIndexRoute
  AuthenticatedArchiveCategoriesIndexRoute: typeof AuthenticatedArchiveCategoriesIndexRoute
  AuthenticatedArchiveProductsIndexRoute: typeof AuthenticatedArchiveProductsIndexRoute
  AuthenticatedArchiveStoresIndexRoute: typeof AuthenticatedArchiveStoresIndexRoute
  AuthenticatedArchiveSuppliersIndexRoute: typeof AuthenticatedArchiveSuppliersIndexRoute
  AuthenticatedArchiveWarehousesIndexRoute: typeof AuthenticatedArchiveWarehousesIndexRoute
  AuthenticatedFinanceFeesIndexRoute: typeof AuthenticatedFinanceFeesIndexRoute
  AuthenticatedFinanceStoreSettlementIndexRoute: typeof AuthenticatedFinanceStoreSettlementIndexRoute
  AuthenticatedFinanceSupplierSettlementIndexRoute: typeof AuthenticatedFinanceSupplierSettlementIndexRoute
  AuthenticatedFinanceVouchersIndexRoute: typeof AuthenticatedFinanceVouchersIndexRoute
  AuthenticatedInventoryChecksIndexRoute: typeof AuthenticatedInventoryChecksIndexRoute
  AuthenticatedInventoryIssuesIndexRoute: typeof AuthenticatedInventoryIssuesIndexRoute
  AuthenticatedInventoryReceiptsIndexRoute: typeof AuthenticatedInventoryReceiptsIndexRoute
  AuthenticatedInventoryStockIndexRoute: typeof AuthenticatedInventoryStockIndexRoute
  AuthenticatedInventoryTransfersIndexRoute: typeof AuthenticatedInventoryTransfersIndexRoute
  AuthenticatedMemberCouponsIndexRoute: typeof AuthenticatedMemberCouponsIndexRoute
  AuthenticatedMemberMembersIndexRoute: typeof AuthenticatedMemberMembersIndexRoute
  AuthenticatedMemberPointsIndexRoute: typeof AuthenticatedMemberPointsIndexRoute
  AuthenticatedOnlineDeliveriesIndexRoute: typeof AuthenticatedOnlineDeliveriesIndexRoute
  AuthenticatedOnlineProductsIndexRoute: typeof AuthenticatedOnlineProductsIndexRoute
  AuthenticatedOnlineStoreConfigIndexRoute: typeof AuthenticatedOnlineStoreConfigIndexRoute
  AuthenticatedOperationCashierShiftsIndexRoute: typeof AuthenticatedOperationCashierShiftsIndexRoute
  AuthenticatedOperationPaymentsIndexRoute: typeof AuthenticatedOperationPaymentsIndexRoute
  AuthenticatedOperationRefundsIndexRoute: typeof AuthenticatedOperationRefundsIndexRoute
  AuthenticatedOperationSalesIndexRoute: typeof AuthenticatedOperationSalesIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedPurchaseReplenishIndexRoute: typeof AuthenticatedPurchaseReplenishIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlatformRouteRoute: AuthenticatedPlatformRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSystemRouteRoute: AuthenticatedSystemRouteRouteWithChildren,
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAnalyticsDailySalesIndexRoute:
    AuthenticatedAnalyticsDailySalesIndexRoute,
  AuthenticatedAnalyticsInventoryIndexRoute:
    AuthenticatedAnalyticsInventoryIndexRoute,
  AuthenticatedAnalyticsProductSalesIndexRoute:
    AuthenticatedAnalyticsProductSalesIndexRoute,
  AuthenticatedArchiveCategoriesIndexRoute:
    AuthenticatedArchiveCategoriesIndexRoute,
  AuthenticatedArchiveProductsIndexRoute:
    AuthenticatedArchiveProductsIndexRoute,
  AuthenticatedArchiveStoresIndexRoute: AuthenticatedArchiveStoresIndexRoute,
  AuthenticatedArchiveSuppliersIndexRoute:
    AuthenticatedArchiveSuppliersIndexRoute,
  AuthenticatedArchiveWarehousesIndexRoute:
    AuthenticatedArchiveWarehousesIndexRoute,
  AuthenticatedFinanceFeesIndexRoute: AuthenticatedFinanceFeesIndexRoute,
  AuthenticatedFinanceStoreSettlementIndexRoute:
    AuthenticatedFinanceStoreSettlementIndexRoute,
  AuthenticatedFinanceSupplierSettlementIndexRoute:
    AuthenticatedFinanceSupplierSettlementIndexRoute,
  AuthenticatedFinanceVouchersIndexRoute:
    AuthenticatedFinanceVouchersIndexRoute,
  AuthenticatedInventoryChecksIndexRoute:
    AuthenticatedInventoryChecksIndexRoute,
  AuthenticatedInventoryIssuesIndexRoute:
    AuthenticatedInventoryIssuesIndexRoute,
  AuthenticatedInventoryReceiptsIndexRoute:
    AuthenticatedInventoryReceiptsIndexRoute,
  AuthenticatedInventoryStockIndexRoute: AuthenticatedInventoryStockIndexRoute,
  AuthenticatedInventoryTransfersIndexRoute:
    AuthenticatedInventoryTransfersIndexRoute,
  AuthenticatedMemberCouponsIndexRoute: AuthenticatedMemberCouponsIndexRoute,
  AuthenticatedMemberMembersIndexRoute: AuthenticatedMemberMembersIndexRoute,
  AuthenticatedMemberPointsIndexRoute: AuthenticatedMemberPointsIndexRoute,
  AuthenticatedOnlineDeliveriesIndexRoute:
    AuthenticatedOnlineDeliveriesIndexRoute,
  AuthenticatedOnlineProductsIndexRoute: AuthenticatedOnlineProductsIndexRoute,
  AuthenticatedOnlineStoreConfigIndexRoute:
    AuthenticatedOnlineStoreConfigIndexRoute,
  AuthenticatedOperationCashierShiftsIndexRoute:
    AuthenticatedOperationCashierShiftsIndexRoute,
  AuthenticatedOperationPaymentsIndexRoute:
    AuthenticatedOperationPaymentsIndexRoute,
  AuthenticatedOperationRefundsIndexRoute:
    AuthenticatedOperationRefundsIndexRoute,
  AuthenticatedOperationSalesIndexRoute: AuthenticatedOperationSalesIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedPurchaseReplenishIndexRoute:
    AuthenticatedPurchaseReplenishIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface authSignInRouteRouteChildren {
  authSignInPlatformRoute: typeof authSignInPlatformRoute
  authSignInTenantRoute: typeof authSignInTenantRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
}

const authSignInRouteRouteChildren: authSignInRouteRouteChildren = {
  authSignInPlatformRoute: authSignInPlatformRoute,
  authSignInTenantRoute: authSignInTenantRoute,
  authSignInIndexRoute: authSignInIndexRoute,
}

const authSignInRouteRouteWithChildren = authSignInRouteRoute._addFileChildren(
  authSignInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authSignInRouteRoute: authSignInRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
