server:
  port: 9000
spring:
  application:
    name: erp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: erp-system
          uri: lb://erp-system
          predicates:
            - Path=/api/v1/admin/auth/**, /api/v1/admin/user/**, /api/v1/admin/role/**, /api/v1/admin/menu/**, /api/v1/admin/tenant/**
        - id: erp-archive
          uri: lb://erp-archive
          predicates:
            - Path=/api/v1/admin/archive/**
        - id: erp-inventory
          uri: lb://erp-inventory
          predicates:
            - Path=/api/v1/admin/inventory/**
        - id: erp-purchase
          uri: lb://erp-purchase
          predicates:
            - Path=/api/v1/admin/purchase/**
        - id: erp-operation
          uri: lb://erp-operation
          predicates:
            - Path=/api/v1/admin/operation/**
        - id: erp-member
          uri: lb://erp-member
          predicates:
            - Path=/api/v1/admin/member/**
