spring:
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
        register-enabled: false
        server-addr: localhost:8848
    gateway:
      routes:
        - id: erp-system-local
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/admin/auth/**,/api/v1/admin/user/**,/api/v1/admin/role/**,/api/v1/admin/menu/**,/api/v1/admin/tenant/**
